require 'acts_as_textcaptcha/version'
require 'acts_as_textcaptcha/errors'
require 'acts_as_textcaptcha/textcaptcha'
require 'acts_as_textcaptcha/textcaptcha_helper'
require 'acts_as_textcaptcha/framework/rails'
